---
vyos_config:
  - " set nat source rule 100 outbound-interface 'eth0' "
  - " set nat source rule 100 source address '10.0.0.0/24' "
  - " set nat source rule 100 translation address masquerade "
  - " set firewall state-policy established action 'accept' "
  - " set firewall state-policy related action 'accept' " 
