---
vyos_router_config:
  - " set nat source rule 100 outbound-interface 'eth0' "
  - " set nat source rule 100 source address '10.0.0.10/32' "
  - " set nat source rule 100 translation address masquerade "
  - " set firewall state-policy established action 'accept' "
  - " set firewall state-policy related action 'accept' " 
  - " set service dns forwarding listen-on eth1 "
  - " set service dns forwarding dhcp eth0 "
