---
vpnvps_target: vps1
resolv_nameservers:
  - 10.0.0.252
resolv_domain: vagrant
pf_file_content: |
  ##macro
  ################
  main="em1"
  table <ftp-openbsd-org> { 129.128.5.191 }
  table <internet-dns> { 10.0.0.252, 10.0.0.253 }
  table <openvpn-clients> {172.31.3.254 }
  table <lan_openvpn_home_site> { 172.31.1.20, 172.31.5.100}
  
  ##global
  ################
  set skip on lo
  #em0 is for vagrant stuff
  set skip on em0
  match in all scrub (no-df)

  ##nat rules
  ################

  ##fw rules
  ################
  pass quick on tun+ tagged TO_VPN
  # further for p2p inbound
  #pass quick on tun+ from  any to ??? tag FROM_VPN
  pass in quick on $main from <lan_openvpn_home_site> to ! self route-to (tun0 192.168.255.1) tag TO_VPN
  
  #enforce policies for outbound interfaces
  pass out quick on $main tagged FROM_VPN

  # firewall is allowed to do all
  pass out quick from self to any
