---

- hosts: all
  tasks:
     - group_by: key=OS_{{ ansible_os_family }}

- name: routers config (vyos)
  hosts: vyos_routers
  gather_facts: False
  connection: local
  vars:
    cli:
      host: "{{ ansible_ssh_host }}"
      port: "{{ ansible_ssh_port }}"
      username: vagrant
      password: vagrant
      transport: cli
  tasks:
    - include: vyos_routers.yml

- name: FreeBSD common tasks
  hosts: OS_FreeBSD
  gather_facts: False
  tasks:
    - pkgng: name=bash state=present
    - file: src=/usr/local/bin/bash dest=/bin/bash state=link owner=root group=wheel
  roles:
    - ansible_motd
    - ansible-resolv

- name: OpenBSD common tasks
  hosts: OS_OpenBSD
  become: true
  gather_facts: False
  roles:
    - ansible_motd
    - ansible-resolv
  tasks:
    - name: generate pf.conf file
      copy: content="{{ pf_file_content }}" dest=/etc/pf.conf mode=0600 owner=root group=wheel
      when: pf_file_content is defined
      register: result

    - name: reload pf service
      command: sh -c "/sbin/pfctl -n -f /etc/pf.conf && /sbin/pfctl -f /etc/pf.conf"
      when: result.changed 

- name: home clients stuff
  hosts: home_clients
  become: true
  gather_facts: False
  tasks:
    - name: install required package (OpenBSD)  
      openbsd_pkg: name={{ item }} state=present
      with_items: [ 'lynx','wget','openvpn']
      when: ansible_os_family  == 'OpenBSD' 

- name: vps stuff
  hosts: openbsd_vps
  become: true
  gather_facts: False
  roles:
    - { role: boxeman.openvpn , openvpn_instance: "{{ openvpn_instance_home}}" , openvpn_instance_name: home }
    - { role: boxeman.openvpn , openvpn_instance: "{{ openvpn_instance_warrior}}" , openvpn_instance_name: warrior }
  tasks:
    - name: fetch vps1 openvpn client file
      fetch: src=/etc/openvpn_home/{{ item }}  dest=tmp/openvpn_home_{{ inventory_hostname }}/{{ item }} flat=yes
      with_items: [ 'client-template.ovpn' ,'keys/ta.key', 'keys/ca.crt','keys/dh2048.pem','keys/issued/home2vps.crt','keys/private/home2vps.key' ]
    - name: fetch opevpn startup script
      fetch: src=/etc/rc.d/openvpn_home dest=tmp/openvpn_home_{{ inventory_hostname }}/rc_script_openvpn_home flat=yes
# later..has to be in vault:
    - name: temporary selfmade auth_file
      copy: content='home2vps:819f04e5706f509de5a6b833d3f561369156820b4240c7c26577b223e59aae97' dest=/etc/openvpn_home/auth_file  

- name: vpnvps1 stuff
  hosts: vpnvps1
  become: true
  tasks:
    - name: add hostfile entries
      lineinfile: dest=/etc/hosts line={{ item }}
      with_items: [ '10.0.0.10	vps1' ]

    - name: install required package (OpenBSD)
      openbsd_pkg: name={{ item }} state=present
      with_items: [ 'openvpn']

    - name: create openvpn client folder
      file: path={{ item }} state=directory owner=root group=wheel mode=0640
      with_items: ['/etc/openvpn_home','/etc/openvpn_home/keys','/etc/openvpn_home/keys/issued','/etc/openvpn_home/keys/private']

# later must be in vault :)
    - name: create auth file
      copy: content='home2vps\ntoto\n' dest=/etc/openvpn_home/auth.txt

    - name: copy openvpn client  cert keys 
      copy: src=tmp/openvpn_home_{{ vpnvps_target }}/{{ item }} dest=/etc/openvpn_home/{{ item }} mode=0600 owner=root group=wheel
      with_items: [  'keys/ca.crt','keys/ta.key', 'keys/dh2048.pem','keys/issued/home2vps.crt','keys/private/home2vps.key' ]

    - name: copy client config file
      copy: src=tmp/openvpn_home_{{ vpnvps_target }}/client-template.ovpn dest=/etc/openvpn_home/openvpn.conf mode=0600 owner=root group=wheel

    - name: update config file
      replace: dest=/etc/openvpn_home/openvpn.conf regexp={{ item.0 }} replace={{ item.1 }}
      with_together:
        - [ ' ta.key',' ca.crt' , ' client.crt' , ' dh2048.pem' , ' client.key', 'auth-user-pass*' ]
        - [' keys/ta.key',' keys/ca.crt',' keys/issued/home2vps.crt',' keys/dh2048.pem',' keys/private/home2vps.key','auth-user-pass auth.txt']

    - name: copy rc script
      copy: src=tmp/openvpn_home_{{ vpnvps_target }}/rc_script_openvpn_home  dest=/etc/rc.d/openvpn_home mode=0755 owner=root group=wheel
  
    - name: start openvpn client
      service: name=openvpn_home state=started enabled=yes       
